version: '2'
services:
  mynextapplicationonjhispter-app:
    image: mynextapplicationonjhispter
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mynextapplicationonjhispter-mysql:3306/mynextapplicationonjhispter?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://mynextapplicationonjhispter-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mynextapplicationonjhispter-elasticsearch:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
  mynextapplicationonjhispter-mysql:
    extends:
      file: mysql.yml
      service: mynextapplicationonjhispter-mysql
  mynextapplicationonjhispter-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mynextapplicationonjhispter-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
